# Environment settings
world_width: 50.0
world_height: 50.0
num_obstacles: 8
num_pois: 4
num_disaster_areas: 1
max_time: 200.0
time_step: 0.2

# Agent settings
num_signal_detectors: 1
num_transport_vehicles: 1
num_rescue_vehicles: 1
num_uavs: 1
num_satellites: 0
num_fixed_stations: 1
max_velocity: 3.0
acceleration: 0.5
battery_consumption_rate: 0.005
uav_max_altitude: 20.0
satellite_orbit_speed: 0.05
fixed_station_range: 15.0
fixed_station_computing_power: 4
communication_range: 10.0
uav_sensor_range: 8.0
uav_monitor_speed: 0.05

# Task settings
num_tasks: 4
new_task_probability: 0.05

# Training settings
num_episodes: 200
max_steps: 300
hidden_dim: 64
actor_lr: 0.0005
critic_lr: 0.001
gamma: 0.99
tau: 0.02
update_every: 20
batch_size: 16

# Evaluation settings
eval_episodes: 10

# Visualization settings
screen_width: 480
screen_height: 480
fps: 20
visualize_every: 10
print_every: 10
save_every: 50

# Model settings
model_save_path: "saved_models/sagin_model_light"

# Memory settings
memory_size: 1000